import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/home.module.css';


export default function Home() {
  return (
    <>
      <Head>
        <title>Alex Belardi Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <h1 className={styles.testing}>TESTING</h1>
    </> 
  )
}
