import { useRef, useEffect, useState } from 'react';
import { BiCaretUp } from 'react-icons/bi';
import Navbar from '../components/Navbar';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/home.module.css';
import Splash from '../components/Splash';
import AboutMe from '../components/AboutMe';
import Intro from '../components/Intro';
import Projects from '../components/Projects';
import Skills from '../components/Skills';


export default function Home(props) {


  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Alex Belardi Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Navbar 
        isOpen={isOpen}
        setIsOpen={setIsOpen}
      />
      <Intro />
      <AboutMe />
      <Projects />
      {isOpen ? 
        <Splash 
        />
        : ''
      }
      <Skills />
      <div className="hidden md:w-11 md:bottom-0 md:flex-col md:right-0 md:flex md:items-center md:mb-2 md:fixed md:h-72 md:">
        <a className="text-lg text-blue-100 writing-vertical font-recoleta-light" href="mailto:afbelardicode@gmail.com">afbelardicode@gmail.com</a>
        <BiCaretUp className="mt-2 mr-1 text-green-300"/>
        <BiCaretUp className="mt-0.5 mr-1 text-green-300"/>
        <BiCaretUp className="mt-0.5 mr-1 text-green-300"/>
        <BiCaretUp className="mt-0.5 mr-1 text-green-300"/>
        <BiCaretUp className="mt-0.5 mr-1 text-green-300"/>
      </div>
      <div className="hidden md:bg-white md:w-11 md:bottom-0 md:left-0 md:block md:fixed md:h-96">

      </div>
    </> 
  )
}
